### ISSUE TITLE
create-repo: repository.yaml doesn't contain sha for metadata tarball

### ISSUE THREAD

**Issue by geaaru** [mudler/luet#138]
create-repo: repository.yaml doesn't contain sha for metadata tarball:
```yaml
description: Mocaccino extra amd64
last_update: "1602061287"
metapath: ""
name: mocaccino-extra
priority: 1
repo_files:
  meta:
    compressiontype: gzip
    filename: repository.meta.yaml.tar.gz
  tree:
    checksums:
      sha256: c9e7abc75e9b4ccf327647af704ef2adccc5c288aad442711f0dcd13eec92989
    compressiontype: gzip
    filename: tree.tar.gz
revision: 15
treepath: ""
type: http
urls:
- http://localhost:8000
```
