### ISSUE TITLE
specfile: copy from

### ISSUE THREAD

**Issue by mudler** [mudler/luet#190]
**Is your feature request related to a problem? Please describe.**
A way to include files in the build container from images from the tree (even if they don't share parents)

**Describe the solution you'd like**
A specfile syntax that transliterate to docker `COPY` commands, but with the resolved image from a list of packages, like `requires`.

For example, in the specfile we can have:
```yaml
steps:
- ...
prelude:
- ...
copy:
- package: 
    category: "foo"
    name: "bar"
    version: ">=0"
#  image: "" # alternatively
  source: "/foo"
  destination: "/bar"
```
transliterates something like to:

`COPY --from=luet/cache:sha /foo /bar`
See: https://docs.docker.com/develop/develop-images/multistage-build/#use-an-external-image-as-a-stage

There should be also a way to expose `COPY` more directly, to allow to copy files from other images external to the tree as well (`image` commented above).

The compiler should also check if the images from the cache in `copy` are available or if it needs to build those explictly first.

**Describe alternatives you've considered**
It basically supersedes #173 as it is more general and supports also the case presented in #173. For example, that is equivalent to copy all files from a (even more) final package docker image with a specfile which is a from `scratch` image

**Additional context**
