### ISSUE TITLE
Allow to define envs to propagate on finalizer with Box

### ISSUE THREAD

**Issue by geaaru** [mudler/luet#241]
At the moment the finalizer executed in "box" mode doesn't contain the environments available from the running shell.

https://github.com/mudler/luet/blob/master/pkg/installer/finalizer.go#L60

The idea is to avoid propagating all the available environments and instead:

* permit to define at configuration level a list of environments that are passed to the box executor.

The configuration syntax could be something like this:
```yaml
finalizer_envs:
    BUILD_ISO: "1"
    env1: "value"
```

* permit to pass these variables from cli with `luet install --finalizer-env key=value`

The same behavior should be applied to the finalizer executed without box mode as well for consistency

**Comment by geaaru** [comment]
At the moment viper loader executes a strings.ToLower() to all keys.
Until this will be configurable on viper the new structure will be:
```yaml
finalizer_envs:
    - key: "BUILD_ISO"
      value: "1"
```
Lower case on envs it's not a good thing if you need to run an extra binary that using normally upper case keys.
