### ISSUE TITLE
Shared fields between packages in a collection

### ISSUE THREAD

**Issue by mudler** [mudler/luet#253]
**Is your feature request related to a problem? Please describe.**
There might be collections with packages between all in the same categories and the same version, e.g.:

```yaml
packages:
- name: "foo"
  category: "bar"
  version: "1.0"
- name: "baz"
  category: "bar"
  version: "1.0"

**Describe the solution you'd like**
A common `name`, `version` and `category` in the `collection.yaml` file, e.g.

```yaml
packages:
- name: "bbb"
- name: "aaa"
- name: "ccc"
  version: "1.0"
  category: "bar"
# ...
version: "0.1"
category: "system"
```

or 

```yaml
packages:
- category: "bbb"
- category: "aaa"
- category: "ccc"
  version: "1.0"
  name: "bar"
# ...
version: "0.1"
name: "baz"
```
**Describe alternatives you've considered**
N/A

**Additional context**
This was brought up by @davidcassany while discussing https://github.com/rancher-sandbox/cOS-toolkit/issues/612
