### ISSUE TITLE
Refactor and split repository.yaml file to improve performance on repository update

### ISSUE THREAD

**Issue by geaaru** [mudler/luet#71]
The idea is to separate the current `repository.yaml` file in two files:

* `repository.yaml`: contains only few pieces of information about repository revision, tree checksum, and other info

* `repository.meta.yaml|repository.meta.yaml.gz`: contains all that is present in the `index` field of the current implementation.

In particular, `repository.yaml` will be with content similar to this:
```yaml
last_update: "1584127975"
name: luet-embedded
priority: 1
revision: 1
treechecksums:
  sha256: aa02841cc1c4bf86cb36953b099be73893192682005061da085a1348df283796
treecompressiontype: gzip
treepath: tree.tar.gz
type: http
urls:
- http://localhost:8000
description: Luet embedded Repo
enable: true
metapath: repository.meta.yaml.gz
metacompressiontype: gzip
```
Where it will add the fields `metapath` and `metacompressiontype`. If these fields aren't present is maintained the previous logic.

And so, the file `repository.meta.yaml` will be with content similar to this:

```yaml
index:
- checksums:
    sha256: 9dd1fdbd9fbbd4e5f34ec213630ffab049dd744b637a725efdf64ea13918005e
  compilationspec:
    env: []
    image: alpine:3.11.3
    includes: []
    package:
      State: ""
      category: distro
      conflicts: []
      description: ""
      id: 0
      license: ""
      name: alpine
      provides: []
      requires: []
      set: false
      uri: []
      use_flags: []
      version: 3.11.3
    prelude: []
    retrieve: []
    seed: ""
    steps: []
    unpack: true
  compressiontype: gzip
  dependencies: []
  path: alpine-distro-3.11.3.package.tar.gz
```

**Comment by geaaru** [comment]
In additional, the idea is to create a struct that will be used for contains `compilationspec` as pass-through of the DefaultPackage to avoid write fields empty. This reduces the size of the metadata file.

**Comment by geaaru** [comment]
New revision

To avoid the dup of the code the idea is move the section of the tree and the metadata under `repo_files` section in a similar way:

```yaml
repo_files:
    tree:
       name: tree.tar.gz
       compressiontype: gzip
       checksums: xxxx
    meta:
       name: repository.meta.tar
       compressiontype: none
       checksums: xxxx
```
